"""initial

Revision ID: 622181602a5f
Revises: 66c14ab4c2b4
Create Date: 2025-06-05 04:25:20.498330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622181602a5f'
down_revision = '66c14ab4c2b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('platform_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('app_running', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('estimated_finish', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_status', schema=None) as batch_op:
        batch_op.drop_column('estimated_finish')
        batch_op.drop_column('app_running')
        batch_op.drop_column('platform_version')
        batch_op.drop_column('platform_name')

    # ### end Alembic commands ###
