"""initial

Revision ID: 66c14ab4c2b4
Revises: a4c7511536dc
Create Date: 2025-06-05 04:20:08.404393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c14ab4c2b4'
down_revision = 'a4c7511536dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('udid', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('udid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_status')
    # ### end Alembic commands ###
